export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8 text-center bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
          Disclaimer
        </h1>
        
        <div className="glass rounded-xl p-8 space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">General Information</h2>
            <p className="text-gray-300 leading-relaxed">
              This disclaimer applies specifically to the chat application on this subdomain 
              of lukeschroeter.de and supplements the general liability provisions of the main domain.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">1. Liability for AI-Generated Content</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              The chat application enables interactions with various AI models. The following applies:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>All responses are generated by external AI models</li>
              <li>The operator has no influence on the generated content</li>
              <li>AI responses may be incorrect, incomplete, or misleading</li>
              <li>Users are solely responsible for evaluating and using the content</li>
              <li>No warranty for accuracy, completeness, or timeliness of AI responses</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">2. Bring-Your-Own-Key Model</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              Since the application operates on the "Bring-Your-Own-Key" principle:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Users bear all costs for API requests themselves</li>
              <li>The operator assumes no liability for incurred costs</li>
              <li>No warranty for the availability of external API services</li>
              <li>Users are responsible for proper management of their API keys</li>
              <li>Misuse of API keys is the user's responsibility</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">3. Technical Availability</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              Regarding technical provision:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>No guarantee for uninterrupted availability of the application</li>
              <li>Maintenance work may lead to temporary outages</li>
              <li>External dependencies (Supabase, OpenRouter, Vercel) may affect availability</li>
              <li>No liability for data loss due to technical problems</li>
              <li>Users should regularly export important chat histories</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">4. User-Generated Content</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              For content entered by users:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Users are solely responsible for their inputs</li>
              <li>No review of user content by the operator</li>
              <li>Users must observe copyrights and other third-party rights</li>
              <li>No liability for legal consequences from user inputs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">5. External Services and Links</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              The application uses external services:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li><strong>OpenRouter:</strong> No control over model availability or quality</li>
              <li><strong>Supabase:</strong> Dependency on external database infrastructure</li>
              <li><strong>Vercel:</strong> Hosting dependency for the application</li>
              <li>No liability for outages or problems with external providers</li>
              <li>Privacy policies of external providers apply additionally</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">6. Data Security</h2>
            <p className="text-gray-300 leading-relaxed mb-3">
              Despite security measures:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>No absolute guarantee for data security</li>
              <li>Users should not enter highly sensitive data in chats</li>
              <li>Regular backups are recommended</li>
              <li>In case of security incidents, information will be provided as soon as possible</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">7. Experimental Nature</h2>
            <p className="text-gray-300 leading-relaxed">
              This application has an experimental nature. Features may change, 
              be added, or removed. Users use the application at their own risk 
              and should be aware that this is a development project.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">8. Limitation of Liability</h2>
            <p className="text-gray-300 leading-relaxed">
              The operator's liability is limited to intent and gross negligence. 
              For slight negligence, liability only exists for breach of essential contractual obligations, 
              and is limited in amount to the damage foreseeable at the time of contract conclusion 
              and typical for the contract.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-purple-300">9. Severability Clause</h2>
            <p className="text-gray-300 leading-relaxed">
              Should individual provisions of this disclaimer be or become invalid or unenforceable, 
              this shall not affect the validity of the remaining provisions.
            </p>
          </section>

          <div className="mt-8 pt-6 border-t border-gray-600">
            <p className="text-sm text-gray-400">
              Last updated: June 2025<br />
              This disclaimer supplements the general liability provisions of lukeschroeter.de
            </p>
          </div>
        </div>
      </div>
    </div>
  );
} 