export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[var(--bg-primary)] via-[var(--bg-secondary)] to-[var(--bg-tertiary)] text-white">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8 text-center bg-gradient-to-r from-[var(--accent)] to-blue-400 bg-clip-text text-transparent">
          Disclaimer
        </h1>
        
        <div className="glass rounded-xl p-8 space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">General Information</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              This disclaimer applies specifically to the Auberon Chat application 
              and provides comprehensive liability information in accordance with EU regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">1. Liability for AI-Generated Content</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              The chat application enables interactions with various AI models. The following applies:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li>All responses are generated by external AI models</li>
              <li>The operator has no influence on the generated content</li>
              <li>AI responses may be incorrect, incomplete, or misleading</li>
              <li>Users are solely responsible for evaluating and using the content</li>
              <li>No warranty for accuracy, completeness, or timeliness of AI responses</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">2. Bring-Your-Own-Key Model</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              Since the application operates on the "Bring-Your-Own-Key" principle:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li>Users bear all costs for API requests themselves</li>
              <li>The operator assumes no liability for incurred costs</li>
              <li>No warranty for the availability of external API services</li>
              <li>Users are responsible for proper management of their API keys</li>
              <li>Misuse of API keys is the user's responsibility</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">3. Technical Availability</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              Regarding technical provision:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li>No guarantee for uninterrupted availability of the application</li>
              <li>Maintenance work may lead to temporary outages</li>
              <li>External dependencies (Supabase, OpenRouter, Vercel) may affect availability</li>
              <li>No liability for data loss due to technical problems</li>
              <li>Users should regularly export important chat histories</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">4. User-Generated Content</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              For content entered by users:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li>Users are solely responsible for their inputs</li>
              <li>No review of user content by the operator</li>
              <li>Users must observe copyrights and other third-party rights</li>
              <li>No liability for legal consequences from user inputs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">5. External Services and Links</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              The application uses external services:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li><strong className="text-white">OpenRouter:</strong> No control over model availability or quality</li>
              <li><strong className="text-white">Supabase:</strong> Dependency on external database infrastructure</li>
              <li><strong className="text-white">Vercel:</strong> Hosting dependency for the application</li>
              <li>No liability for outages or problems with external providers</li>
              <li>Privacy policies of external providers apply additionally</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">6. Data Security</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed mb-3">
              Despite security measures:
            </p>
            <ul className="list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4">
              <li>No absolute guarantee for data security</li>
              <li>Users should not enter highly sensitive data in chats</li>
              <li>Regular backups are recommended</li>
              <li>In case of security incidents, information will be provided as soon as possible</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">7. Experimental Nature</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              This application has an experimental nature. Features may change, 
              be added, or removed. Users use the application at their own risk 
              and should be aware that this is a development project.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">8. Limitation of Liability</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              The operator's liability is limited to intent and gross negligence. 
              For slight negligence, liability only exists for breach of essential contractual obligations, 
              and is limited in amount to the damage foreseeable at the time of contract conclusion 
              and typical for the contract.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[var(--accent)]">9. Severability Clause</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Should individual provisions of this disclaimer be or become invalid or unenforceable, 
              this shall not affect the validity of the remaining provisions.
            </p>
          </section>

          <div className="mt-8 pt-6 border-t border-[var(--glass-border)]">
            <p className="text-sm text-[var(--text-tertiary)]">
              Last updated: June 2025<br />
              This disclaimer complies with EU liability regulations and consumer protection laws
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
